# Use root/example as user/password credentials

services:
  web:
    build: api/.
    ports:
      - "81:80"
  db:
    # build: .\database\
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
